name: JavaScript CI - Node.js Application

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'knox-tf-webapp-2502'   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'app' #'app/myExpressApp'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.17.0' 
  AZURE_KEY_VAULT: "knox-tf-kv-2502"               # set this to the node version to use

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm install @azure/keyvault-keys
        npm install @azure/identity
        npm run build --if-present
        npm run test --if-present
      working-directory:  ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
               
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    # Azure logout 
    - name: logout
      run: |
        az logout